#!/bin/bash
# wget https://k-sergey-v.github.io/Scrypt/deb--stack-nodejs-n8n && sudo bash deb--stack-nodejs-n8n
# version by 2025-07-29
# Sergey Krichko

wget https://k-sergey-v.github.io/Scrypt/deb-nodejs
sudo bash deb-nodejs 24

wget https://k-sergey-v.github.io/Scrypt/deb-n8n-npm 
sudo bash deb-n8n-npm