#!/bin/bash
# wget https://k-sergey-v.github.io/Scrypt/deb--config-newuser && sudo bash deb--config-newuser
# version by 2025-07-29
# Sergey Krichko

set -e

# 1.[NEWUSER]
echo "[NEWUSER] >>> create user..."
read -p "Insert name new user: " USERNAME

# Checking if the user exists
if id "$USERNAME" &>/dev/null; then
    echo "[NEWUSER] >>> add [-] >>> User '$USERNAME' already exists."
    usermod -aG sudo "$USERNAME"
    echo "[NEWUSER] >>> sudo [✓] >>> User $USERNAME added to sudo group"
else
    # === insert password ===
    read -s -p "[NEWUSER] >>> password >>> Insert password for $USERNAME: " PASSWORD
    echo
    read -s -p "[NEWUSER] >>> password >>> Repeat password: " PASSWORD2
    echo

    if [ "$PASSWORD" != "$PASSWORD2" ]; then
        echo "[NEWUSER] >>> password [!] >>> Passwords do not match. Aborting."
        exit 1
    fi

    # === Create user ===
    echo "[NEWUSER] >>> add [+] >>> Create user $USERNAME..."
    useradd -m -s /bin/bash "$USERNAME"
    echo "$USERNAME:$PASSWORD" | chpasswd
    echo "[NEWUSER] >>> add [✓] >>> User $USERNAME created"

    # === Add group sudo ===
    usermod -aG sudo "$USERNAME"
    echo "[NEWUSER] >>> sudo [✓] >>> User $USERNAME added to sudo group"
fi