#!/bin/bash
# wget https://k-sergey-v.github.io/Scrypt/deb-n8n-npm && sudo bash deb-n8n-npm
# version by 2025-07-29
# Sergey Krichko

# 0. [SYSTEM]
echo "[SYSTEM] >>> Update and Upgrade"
sudo apt update -y
sudo apt upgrade -y
echo "[SYSTEM][✓] >>> update completed!"


# 1. Installing the required packages for N8N
echo "[SYSTEM] >>> installing need soft for N8N-NPM"
sudo apt install -y curl gnupg build-essential ca-certificates git
echo "[SYSTEM][✓] >>> Installing completed!"

# 2. create a system group and user n8n
echo "[N8N] >>> create user n8n"
sudo adduser --system --gecos "n8n service user" --group --home /var/lib/n8n --shell /usr/sbin/nologin --disabled-password n8n
sudo chown -R n8n:n8n /var/lib/n8n
sudo chmod 750 /var/lib/n8n


# To install n8n globally, use npm:
echo "[N8N] >>> installing..." 
sudo npm install n8n -g
echo "[N8N] >>> installed = $(n8n --version)"

#To install next:
echo "[N8N] >>> update to next"
sudo npm install -g n8n@next

#After the installation, start n8n by running:
echo "[N8N][✓] Версия N8N = $(n8n --version)"


# sudo tee /etc/systemd/system/n8n.service > /dev/null << 'EOF'
# [Unit]
# Description=n8n workflow automation
# After=network.target

# [Service]
# Type=simple
# User=n8n
# EnvironmentFile=/home/n8n/.n8n/.env
# ExecStart=/usr/bin/n8n
# Restart=on-failure
# # Увеличиваем лимит открытых файлов (рекомендуется для высокой нагрузки)
# LimitNOFILE=65536

# [Install]
# WantedBy=multi-user.target
# EOF

# sudo systemctl daemon-reload


# sudo systemctl enable n8n
# sudo systemctl start n8n