#!/bin/bash
# wget https://k-sergey-v.github.io/Scrypt/deb-nodejs && sudo bash deb-nodejs
# version by 2025-07-25
# Sergey Krichko

if [ -z "$1" ]; then
    echo "Ошибка: не указана версия NodeJS"
    exit 1
fi
nodejsversion=$1

# 1. Обновление пакетов
sudo apt update
sudo apt upgrade -y

# 2. Устанока необходимых пакетов
sudo apt install -y curl

# 3. Установка NodeJS
curl -fsSL https://deb.nodesource.com/setup_$nodejsversion.x | sudo -E bash -
sudo apt install -y nodejs

# проверяем
echo "[nodejs][✓] Версия NodeJS " 
node -v
echo "[nodejs][✓]  Версия NPM " 
npm -v