#!/bin/bash
# wget https://k-sergey-v.github.io/Scrypt/deb--config && bash deb--config
# version by 2025-05-29
# Sergey Krichko

if [ "$(id -u)" -ne 0 ]; then
    echo "Этот скрипт нужно запускать от root"
    exit 1
fi

echo "[update] Обновление системы..."
# Update and Upgrade system
apt update -y && apt upgrade -y
echo "[update][✓] система обновлена"

echo "[sudo] Установка sudo..."
# Установим sudo, если не установлен
if ! command -v sudo &> /dev/null; then
    apt install -y sudo
    echo "[sudo][✓] sudo установлен"
else
    echo "[sudo][-] sudo уже установлен ранее"
fi

# config-netsoft
wget https://k-sergey-v.github.io/Scrypt/deb--config-netsoft
bash deb--config-netsoft

# config-NEWUSER
wget https://k-sergey-v.github.io/Scrypt/deb--config-newuser
bash deb--config-newuser

# config-SSH
wget https://k-sergey-v.github.io/Scrypt/deb--config-ssh
bash deb--config-ssh

#config-IP
wget https://k-sergey-v.github.io/Scrypt/deb--config-ip
bash deb--config-ip