#!/bin/bash
# wget https://raw.githubusercontent.com/K-Sergey-V/Scrypt/refs/heads/main/deb-bs.sh
# Change settings
# version by 2025-05-29
# Sergey Krichko

# Update and Upgrade system
apt update && apt upgrade
apt install -y sudo

# Add user
read -p "Enter new user => " newuser
adduser $newuser
passwd $newuser

# config sudo

ADD_LINE="$newuser ALL=(ALL:ALL) ALL"
AFTER_LINE='root    ALL=(ALL:ALL) ALL'
FILE='/etc/sudoers'

# Экранируем переменные для sed
escaped_add_line=$(printf '%s\n' "$ADD_LINE" | sed 's/[&/\]/\\&/g')
escaped_after_line=$(printf '%s\n' "$AFTER_LINE" | sed 's/[&/\]/\\&/g')

# Добавляем строку после нужной
sudo sed -i "/^$escaped_after_line$/a $escaped_add_line" "$FILE"


#Port 44322


#PermitRootLogin yes


