#!/bin/bash
# wget https://k-sergey-v.github.io/Scrypt/deb-nodejs && sudo bash deb-nodejs 24
# version by 2025-07-29
# Sergey Krichko

if [ -z "$1" ]; then
    echo "Ошибка: не указана версия NodeJS"
    exit 1
fi
nodejsversion=$1

# 0. [SYSTEM]
echo "[SYSTEM] >>> Update and Upgrade"
sudo apt update -y
sudo apt upgrade -y
echo "[SYSTEM][✓] >>> update completed!"

# 1. Installing the required packages for NodeJS
echo "[SYSTEM] >>> Installing the required packages for NodeJS"
sudo apt install -y curl
echo "[SYSTEM][✓] >>> Installing completed!"

# 2. Installing NodeJS
echo "[NODEJS] >>> installing..." 
curl -fsSL https://deb.nodesource.com/setup_$nodejsversion.x | sudo -E bash -
sudo apt install -y nodejs
echo "[NODEJS][✓] >>> Installing completed!"

# 3. Проверяем
echo "[NODEJS][✓] Версия NodeJS = $(node -v) "
echo "[NODEJS][✓] Версия NPM = $(npm -v)"