#!/bin/bash
# wget https://k-sergey-v.github.io/Scrypt/deb-nodejs && sudo bash deb-nodejs 24
# version by 2025-07-25
# Sergey Krichko

if [ -z "$1" ]; then
    echo "Ошибка: не указана версия NodeJS"
    exit 1
fi
nodejsversion=$1

# 0. Обновление пакетов системы
echo "[SYSTEM] >>> Update and Upgrade"
sudo apt update -y
sudo apt upgrade -y

# 1. Устанока необходимых пакетов
echo "[SYSTEM] >>> installing need soft >>> nodejs"
sudo apt install -y curl

# 2. Установка NodeJS
echo "[nodejs] >>> installing..." 
curl -fsSL https://deb.nodesource.com/setup_$nodejsversion.x | sudo -E bash -
sudo apt install -y nodejs

# 3. Проверяем
echo "[nodejs][✓]" 
echo "Версия NodeJS = $(node -v) "
echo "[nodejs][✓]" 
echo "Версия NPM = $(npm -v)"